volumes:
  data_dev:
  shared_data:

services:
  db:
    image: postgres:17
    container_name: rails_template_mazer_db_dev
    volumes:
      - data_dev:/var/lib/postgresql/data
      - shared_data:/var/shared
    env_file: .env.dev
    # restart: always
    ports:
      - "5437:5432"