default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['POSTGRES_DB']%>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: <%= ENV['POSTGRES_PORT'] || '5432' %>
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: rails_template_mazer_development

test:
  <<: *default
  database: rails_template_mazer_test


production:
  primary: &primary_production
    <<: *default
    database: rails_template_mazer_production
    username: rails_template_mazer
    password: <%= ENV["RAILS_TEMPLATE_MAZER_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rails_template_mazer_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rails_template_mazer_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rails_template_mazer_production_cable
    migrations_paths: db/cable_migrate
